### ISSUE TITLE
Add HoneyGinger to Awsome Pharo

### ISSUE THREAD

**Issue by samWson** [tomooda/HoneyGinger#1]
I found your project on through [Pharo weekly](https://pharoweekly.wordpress.com/) and the [success stories](https://pharo.org/success/HoneyGinger) on Pharo.org. With your permission I'd like to get HoneyGinger listed on [Awsome Pharo](https://github.com/pharo-open-documentation/awesome-pharo).

Awsome Pharo is a community driven collection of Pharo libraries, tools, frameworks etc. Listing HoneyGinger there would give more visibility to the project and help other people find and use it. If your happy with this let me know and I'll open an issue on Awsome Pharo to get HoneyGinger listed.

**Comment by tomooda** [comment]
Yes, please! I'd be very happy with HoneyGinger being my first recommended project on the list (after 2 of my self-nominated ones. :-)

**Comment by samWson** [comment]
Great. I've opened an [issue](https://github.com/pharo-open-documentation/awesome-pharo/issues/85). I've proposed that it should go in the *Scientific libraries* section but I'll admit that I know very little about fluid dynamics so correct me if I'm wrong.
